/*
  This class has been generated by the Code Generator
*/

package com.opentext.apps.cc.custom;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;


public class ContractDates extends ContractDatesBase
{
    public ContractDates()
    {
        this((BusObjectConfig)null);
    }

    public ContractDates(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.opentext.apps.cc.custom.ContractDates> getContractDatesObjects(com.cordys.cpc.bsf.query.Cursor cursor)
    {
        // TODO implement body
        return null;
    }

    public void onInsert()
    {
    }

    public void onUpdate()
    {
    }

    public void onDelete()
    {
    }

}
