/*
  This class has been generated by the Code Generator
*/

package com.opentext.apps.cc.custom;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;


public abstract class ContractDatesBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_InitialExpiryDate = "InitialExpiryDate";
    public final static String ATTR_RenewalCycle = "RenewalCycle";
    public final static String ATTR_CurrentStartDate = "CurrentStartDate";
    public final static String ATTR_NextExpiryDate = "NextExpiryDate";
    public final static String ATTR_TotalContractTenure = "TotalContractTenure";
    public final static String ATTR_TerminationNoticePeriodDate = "TerminationNoticePeriodDate";
    public final static String ATTR_CurrentEndDate = "CurrentEndDate";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(ContractDates.class);
            s_classInfo.setUIDElements(new String[]{});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_InitialExpiryDate);
                ai.setJavaName(ATTR_InitialExpiryDate);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RenewalCycle);
                ai.setJavaName(ATTR_RenewalCycle);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_RenewalCycle);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CurrentStartDate);
                ai.setJavaName(ATTR_CurrentStartDate);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_NextExpiryDate);
                ai.setJavaName(ATTR_NextExpiryDate);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TotalContractTenure);
                ai.setJavaName(ATTR_TotalContractTenure);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TerminationNoticePeriodDate);
                ai.setJavaName(ATTR_TerminationNoticePeriodDate);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CurrentEndDate);
                ai.setJavaName(ATTR_CurrentEndDate);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public ContractDatesBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getInitialExpiryDate()
    {
        return getStringProperty(ATTR_InitialExpiryDate);
    }

    public void setInitialExpiryDate(String value)
    {
        setProperty(ATTR_InitialExpiryDate, value, 0);
    }

    public int getRenewalCycle()
    {
        return getIntProperty(ATTR_RenewalCycle);
    }

    public void setRenewalCycle(int value)
    {
        setProperty(ATTR_RenewalCycle, value, 0);
    }

    public String getCurrentStartDate()
    {
        return getStringProperty(ATTR_CurrentStartDate);
    }

    public void setCurrentStartDate(String value)
    {
        setProperty(ATTR_CurrentStartDate, value, 0);
    }

    public String getNextExpiryDate()
    {
        return getStringProperty(ATTR_NextExpiryDate);
    }

    public void setNextExpiryDate(String value)
    {
        setProperty(ATTR_NextExpiryDate, value, 0);
    }

    public String getTotalContractTenure()
    {
        return getStringProperty(ATTR_TotalContractTenure);
    }

    public void setTotalContractTenure(String value)
    {
        setProperty(ATTR_TotalContractTenure, value, 0);
    }

    public String getTerminationNoticePeriodDate()
    {
        return getStringProperty(ATTR_TerminationNoticePeriodDate);
    }

    public void setTerminationNoticePeriodDate(String value)
    {
        setProperty(ATTR_TerminationNoticePeriodDate, value, 0);
    }

    public String getCurrentEndDate()
    {
        return getStringProperty(ATTR_CurrentEndDate);
    }

    public void setCurrentEndDate(String value)
    {
        setProperty(ATTR_CurrentEndDate, value, 0);
    }


}
