/*
  This class has been generated by the Code Generator
*/

package com.opentext.apps.cc.custom;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;


public class RemainingContractValueOutputObject extends RemainingContractValueOutputObjectBase
{
    public RemainingContractValueOutputObject()
    {
        this((BusObjectConfig)null);
    }

    public RemainingContractValueOutputObject(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.opentext.apps.cc.custom.RemainingContractValueOutputObject> getRemainingContractValueOutputObjectObjects(com.cordys.cpc.bsf.query.Cursor cursor)
    {
        // TODO implement body
        return null;
    }

    public void onInsert()
    {
    }

    public void onUpdate()
    {
    }

    public void onDelete()
    {
    }

}
