/*
  This class has been generated by the Code Generator
*/

package com.opentext.apps.cc.custom;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;


public abstract class RemainingContractValueOutputObjectBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_TotalContractValue = "TotalContractValue";
    public final static String ATTR_RemainingContractValue = "RemainingContractValue";
    public final static String ATTR_TotalContractValueInUSD = "TotalContractValueInUSD";
    public final static String ATTR_RemainingContractValueInUSD = "RemainingContractValueInUSD";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(RemainingContractValueOutputObject.class);
            s_classInfo.setUIDElements(new String[]{});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TotalContractValue);
                ai.setJavaName(ATTR_TotalContractValue);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_TotalContractValue);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RemainingContractValue);
                ai.setJavaName(ATTR_RemainingContractValue);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_RemainingContractValue);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TotalContractValueInUSD);
                ai.setJavaName(ATTR_TotalContractValueInUSD);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_TotalContractValueInUSD);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RemainingContractValueInUSD);
                ai.setJavaName(ATTR_RemainingContractValueInUSD);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_RemainingContractValueInUSD);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public RemainingContractValueOutputObjectBase(BusObjectConfig config)
    {
        super(config);
    }

    public double getTotalContractValue()
    {
        return getDoubleProperty(ATTR_TotalContractValue);
    }

    public void setTotalContractValue(double value)
    {
        setProperty(ATTR_TotalContractValue, value, 0);
    }

    public double getRemainingContractValue()
    {
        return getDoubleProperty(ATTR_RemainingContractValue);
    }

    public void setRemainingContractValue(double value)
    {
        setProperty(ATTR_RemainingContractValue, value, 0);
    }

    public double getTotalContractValueInUSD()
    {
        return getDoubleProperty(ATTR_TotalContractValueInUSD);
    }

    public void setTotalContractValueInUSD(double value)
    {
        setProperty(ATTR_TotalContractValueInUSD, value, 0);
    }

    public double getRemainingContractValueInUSD()
    {
        return getDoubleProperty(ATTR_RemainingContractValueInUSD);
    }

    public void setRemainingContractValueInUSD(double value)
    {
        setProperty(ATTR_RemainingContractValueInUSD, value, 0);
    }


}
